#
# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Yasson

on:
  pull_request:
  push:

jobs:
  name: Test on JDK ${{ matrix.java_version }}
  runs-on: ubuntu-latest

  strategy:
    matrix:
      java_version: [ 11, 17-ea ]

  steps:
    - name: Checkout for build
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
          ava-version: ${{ matrix.java_version }}
    - name: Chestyle
      run: cd yasson && mvn -B -Pstaging checkstyle:checkstyle
    - name: Copyright
      run: bash etc/copyright.sh
    - name: Yasson install
      run: mvn -U -C -Pstaging clean install
    - name: Yasson TCK
      run: cd yasson-tck && mvn -U -B -Pstaging test
